.TH LX-CONTROL-CENTER 1 "November 2016"

.SH NAME
lx-control-center \- Apply settings for LXDE environment.

.SH DESCRIPTION
.B lx-control-center
lets you apply settings for LXDE environment.

.SH AUTHORS
This manual page was written by Julien Lavergne for the Ubuntu Project, but may be used by others. Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 2 or any later version published by the Free Software Foundation.

On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common-licenses/GPL-2.
